export const Talents = {
  talents: {
    Adversary: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "All-Terrain Driver": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Anatomy Lessons": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Armor Master": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Bacta Specialist": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Bad Motivator": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    Balance: {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    "Basic Combat Training": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    Bloodied: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Body Guard": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    "Bought Info": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Brace": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    "Brilliant Evasion": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Bypass Security": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Careful Planning": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Clever Solution": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    Codebreaker: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Command: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Commanding Presence": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Confidence: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Contraption: {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Convincing Demeanor": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Coordinated Assault": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    "Creative Killer": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Crippling Blow": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Dead to Rights": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Dead to Rights (Improved)": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Deadly Accuracy": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Debilitating Shot": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Dedication": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Defensive Driving": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Defensive Slicing": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Defensing Slicing (Improved)": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Defensive Stance": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    Disorient: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Dodge: {activation: "Active", activation_type: "Out of Turn", ranked: true, description: "", page_aoe: 0},
    Durable: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Dynamic Fire": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    Enduring: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Exhaust Port": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Expert Tracker": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Familiar Suns": {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    "Feral Strength": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Field Commander": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Field Commander (Improved)": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Fine Tuning": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Fire Control": {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    Forager: {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Force of Will": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Force Rating": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Form on Me": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Frenzied Attack": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Full Stop": {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    "Full Throttle": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Full Throttle (Improved)": {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    "Full Throttle (Supreme)": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Galaxy Mapper": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Gearhead: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Greased Palms": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    Grit: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Hard Headed": {activation: "Active", activation_type: "Action", ranked: true, description: "", page_aoe: 0},
    "Hard Headed (Improved)": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Heightened Awareness": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Heroic Fortitude": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Hidden Storage": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Hold Together": {activation: "Active", activation_type: "Out of Turn", ranked: false, description: "", page_aoe: 0},
    "Incite Rebellion": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    Indistinguishable: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Insight: {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Inspiring Rhetoric": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Inspiring Rhetoric (Improved)": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Inspiring Rhetoric (Supreme)": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Intense Focus": {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    "Intense Presence": {activation: "Active", activation_type: "Out of Turn", ranked: false, description: "", page_aoe: 0},
    Intimidating: {activation: "Active", activation_type: "Out of Turn", ranked: true, description: "", page_aoe: 0},
    Inventor: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Invigorate: {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "It's Not That Bad": {activation: "Active", activation_type: "Out of Turn", ranked: false, description: "", page_aoe: 0},
    "Jump Up": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Jury Rigged": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Kill with Kindness": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Knockdown: {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Know Somebody": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Knowledge Specialization": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Known Schematic": {activation: "Active", activation_type: "Maneuver", ranked: false, description: "", page_aoe: 0},
    "Let's Ride": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Lethal Blows": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Master Doctor": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master Driver": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master Grenadier": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Master Leader": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master Merchant": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master of Shadows": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master Pilot": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master Slicer": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Master Starhopper": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Mental Fortress": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Brawler": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Charmer": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Doctor": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Driver": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Enforcer": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Hunter": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Leader": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Marksman": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Negotiator": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Outdoorsman": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Pilot": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Programmer": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Rogue": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Scholar": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Natural Tinkerer": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Nobody's Fool": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Outdoorsman: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Overwhelm Defenses": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Physical Training": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Plausible Deniability": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Point Blank": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Powerful Blast": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Quick Draw": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Quick Fix": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Quick Strike": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Rapid Reaction": {activation: "Active", activation_type: "Out of Turn", ranked: true, description: "", page_aoe: 0},
    "Rapid Recovery": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Redundant Systems": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    Researcher: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Resolve: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Respected Scholar": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Scathing Tirade": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Scathing Tirade (Improved)": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Scathing Tirade (Supreme)": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Second Wind": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Selective Detonation": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Sense Danger": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    Shortcut: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Side Step": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    "Situational Awareness": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Sixth Sense": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Skilled Jockey": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Skilled Slicer": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Sleight of Mind": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Smooth Talker": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Sniper Shot": {activation: "Active", activation_type: "Incidental", ranked: true, description: "", page_aoe: 0},
    "Soft Spot": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Solid Repairs": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Sound Investment": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Spare Clip": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Speaks Binary": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Stalker: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Steely Nerves": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Stim Application": {activation: "Active", activation_type: "Action", ranked: false, description: "", page_aoe: 0},
    "Stim Application (Improved)": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Stim Application (Supreme)": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Stimpack Specialization": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Street Smarts": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Stroke of Genius": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Strong Arm": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Stunning Blow": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Stunning Blow (Improved)": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Superior Reflexes": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    Surgeon: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Swift: {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Tactical Combat Training": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Targeted Blow": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Technical Aptitude": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Time to Go": {activation: "Active", activation_type: "Out of Turn", ranked: false, description: "", page_aoe: 0},
    "Time to Go (Improved)": {activation: "Active", activation_type: "Out of Turn", ranked: false, description: "", page_aoe: 0},
    Tinkerer: {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Touch of Fate": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Toughened": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Tricky Target": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "True Aim": {activation: "Active", activation_type: "Maneuver", ranked: true, description: "", page_aoe: 0},
    "Uncanny Reactions": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Uncanny Senses": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    Unstoppable: {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Utility Belt": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    "Vehicle Combat Training": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Well Rounded": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Well Traveled": {activation: "Passive", ranked: false, description: "", page_aoe: 0},
    "Wheel and Deal": {activation: "Passive", ranked: true, description: "", page_aoe: 0},
    "Works Like a Charm": {activation: "Active", activation_type: "Incidental", ranked: false, description: "", page_aoe: 0},
    isRanked: function(talent) {return this[talent].ranked},
    getActivation: function(talent) {return this[talent].activation},
    getActivationType: function(talent) {
      if (this.getActivation(talent) == "Active") {return this[talent].activation_type;}
      else {return null;}
    }
  },
  get all_talents() {
    var list = [];
    for (var talent in this.talents) {list.push(talent);}
    return list;
  },
  get ranked_talents() {
    var list = [];
    for (const talent in this.talents) {if (this.isRanked(talent)) {list.push(talent);}}
    return list;
  },
  isRanked: function(talent) {return this.talents.isRanked(talent);},
  getActivation: function(talent) {return this.talents.getActivation(talent);},
  getActivationType: function(talent) {return this.talents.getActivationType(talent);}
}